install.packages("writexl", repos = "https://cloud.r-project.org" )
install.packages('openxlsx',repos ='https://cloud.r-project.org' )

library(openxlsx)
library(ggplot2)
library(tidyr)
library(readxl)
library(dplyr)
library(janitor)
library(tidyverse)
library(str2str)
library(conflicted)
library(rlang)
library(writexl)
conflict_prefer('select','dplyr','MASS')
conflict_prefer('filter','dplyr','MASS')
conflict_prefer('filter','dplyr','stats')
conflicts_prefer(dplyr::filter)


